chm:
  _001:
    mu: 29.136810302734375
    n: 424127
    std: 5.059322357177734
  _010:
    mu: 27.330501556396484
    n: 331027
    std: 6.319409370422363
  _011:
    mu: 28.23365592956543
    n: 755154
    std: 5.794953346252441
  _100:
    mu: 29.6536808013916
    n: 752512
    std: 9.09404182434082
  _101:
    mu: 29.395244598388672
    n: 1176639
    std: 7.363151550292969
  _110:
    mu: 28.49209213256836
    n: 1083539
    std: 7.916279315948486
  _111:
    mu: 28.706998825073242
    n: 1507666
    std: 7.0994954109191895
  _eq:
    mu: 28.706998825073242
    n: 1507666
    std: 7.0994954109191895
info:
  description: CHM normalization parameters
  encoding: '001: FirstSite only, 010: Second Site, 100: Third Site'
  version: '1.0'
