chm:
  _001:
    mu: 29.136810302734375
    n: 424127
    std: 5.059319972991943
  _010:
    mu: 27.330501556396484
    n: 331027
    std: 6.319406986236572
  _011:
    mu: 28.345002320026218
    n: 755154
    std: 5.611687865810269
  _100:
    mu: 29.79595947265625
    n: 753596
    std: 9.429980278015137
  _101:
    mu: 29.5585836550901
    n: 1177723
    std: 7.85599807406007
  _110:
    mu: 29.043501579318452
    n: 1084623
    std: 8.480633136144107
  _111:
    mu: 29.069731736028462
    n: 1508750
    std: 7.518862605606749
info:
  description: CHM normalization parameters
  encoding: '001: FirstSite only, 010: Second Site, 100: Third Site'
  version: '1.0'
